import { EmployeesResponse } from 'src/app/shared/interfaces/employeesResponse';

export const mockEmployees: EmployeesResponse = {
  data: [
    {
      id: 187,
      zohoUniqueId: '340237000006978097',
      name: 'Abraham Stanley Morales Carranza',
      username: 'asmorales',
      email: 'asmorales@applaudostudios.com',
      image:
        'https://bkt-gatekeeper-applaudo.s3.amazonaws.com/employee/766068008',
      department: 'Operations',
      designation: 'Front - End Developer',
      developerType: 'Web Developer',
      technology: 'Angular',
      platform: 'Web',
      dateOfBirth: '1997-04-24T00:00:00.000Z',
      dateOfJoining: '2021-12-06T00:00:00.000Z',
      addedTime: null,
      gender: '',
      reportingTo: 'Raul Chacon PS-CR001',
      employeeTtype: '',
      zohoPeopleRole: 'Team member',
      enabled: true,
      firstAttempt: false,
      twoFactorEnabled: true,
      employeeID: '',
      role: {
        id: 1,
        name: 'root',
        description: 'Root user',
        default: false,
        weight: 1,
      },
      createdAt: '2021-12-10T01:30:14.298Z',
      updatedAt: '2022-04-18T21:55:47.019Z',
    },
    {
      id: 127,
      zohoUniqueId: 'admin_id',
      name: 'admin',
      username: 'admin',
      email: 'admin@applaudostudios.com',
      image: 'https://contacts.zoho.com/file?ID=-1&fs=thumb',
      department: "null",
      designation: "null",
      developerType: "null",
      technology: "null",
      platform: "null",
      dateOfBirth: "null",
      dateOfJoining: "null",
      addedTime: null,
      gender: "null",
      reportingTo: "null",
      employeeTtype: "null",
      zohoPeopleRole: "null",
      enabled: true,
      firstAttempt: false,
      twoFactorEnabled: true,
      employeeID: '',
      role: {
        id: 2,
        name: 'admin',
        description: 'Administrator user',
        default: false,
        weight: 2,
      },
      createdAt: '2020-07-20T17:57:18.979Z',
      updatedAt: '2022-06-04T00:32:38.663Z',
    },
    {
      id: 140,
      zohoUniqueId: '340237000002796085',
      name: 'Alejandro Granados',
      username: 'agranados',
      email: 'agranados@applaudostudios.com',
      image:
        'https://bkt-gatekeeper-applaudo.s3.amazonaws.com/employee/726694924',
      department: "null",
      designation: "null",
      developerType: "null",
      technology: "null",
      platform: "null",
      dateOfBirth: "null",
      dateOfJoining: "null",
      addedTime: null,
      gender: "null",
      reportingTo: "null",
      employeeTtype: "null",
      zohoPeopleRole: "null",
      enabled: true,
      firstAttempt: false,
      twoFactorEnabled: false,
      employeeID: '',
      role: {
        id: 3,
        name: 'regular',
        description: 'Regular user',
        default: true,
        weight: 3,
      },
      createdAt: '2020-10-08T23:54:02.820Z',
      updatedAt: '2022-04-05T21:55:41.512Z',
    },
  ],
};
